apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: marvel-dev
  annotations:
    run.googleapis.com/description: marvel-dev
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cloudsql-instances: ${DEV_CLOUDSQL_CONNECTION_STRING} # just for illustration
    spec:
      containers:
        - name: marvel-dev
          image: us-central1-docker.pkg.dev/{DEV_GCP_PROJECT_ID}/marvel-registry/marvel:latest
          ports:
            - name: http1
              containerPort: 80
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
