apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: marvel
  labels: 
    app: marvel
description: Cloud Deploy Pipeline for Marvel
serialPipeline:
  stages:
    - targetId: marvel-dev
      profiles:
        - dev
    - targetId: marvel-prod
      profiles:
        - prod
