apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: marvel-dev
  labels: {}
requireApproval: false
run:
  location: projects/{DEV_GCP_PROJECT_ID}/locations/us-central1

---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: marvel-prod
  labels: {}
requireApproval: true
run:
  location: projects/{PROD_GCP_PROJECT_ID}/locations/us-central1
