apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: marvel-prod
  annotations:
    run.googleapis.com/description: marvel-prod
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "2"
        run.googleapis.com/startup-cpu-boost: "true"
        run.googleapis.com/cloudsql-instances: ${PROD_CLOUDSQL_CONNECTION_STRING} # just for illustration
    spec:
      containers:
        - name: marvel-dev
          image: us-central1-docker.pkg.dev/{DEV_GCP_PROJECT_ID}/marvel-registry/marvel:latest
          ports:
            - name: http1
              containerPort: 80
          resources:
            limits:
              cpu: 4000m
              memory: 2Gi
          startupProbe:
            timeoutSeconds: 600
            periodSeconds: 600
            failureThreshold: 1
            tcpSocket:
              port: 80
