steps:
- id: 'Pre Trigger Status Message'
  name: 'alpine/curl'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
    ls -la && pwd
    curl -X POST -H 'Content-type: application/json' --data '{"channel":"${_CHANNEL_ID}","blocks":[{"type":"section","text":{"type":"mrkdwn","text":"Build Started for *$TRIGGER_NAME*"}}]}' "${_SLACK_WEBHOOK}"

- id: 'Download Terraform Artifact from JFrog'
  name: 'docker.bintray.io/jfrog/artifactory-cpp-ce'
  args:
  - '-c'
  - |
    ls -la && pwd
    curl -H "${_JFROG_API}" -XGET "${_JFROG_ARTIFACTORY_URL}/tf/tf_plan" --output tf_plan
  