steps:
- id: 'Pre Trigger Status Message'
  name: 'ubuntu'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
    ls -la && pwd
    curl -X POST -H 'Content-type: application/json' --data '{"channel":"${_CHANNEL_ID}","blocks":[{"type":"section","text":{"type":"mrkdwn","text":"Build Started"}}]}' "${_SLACK_WEBHOOK}"
- name: ubuntu
  args:
  - echo
  - hello 
  