steps:
- id: 'Terraform Initialize'
  name: 'hashicorp/terraform:1.0.0'
  dir: 'scripts/cloudbuild/gce-tf'
  args: ['init']

- id: 'Terraform Format and Validate'
  name: 'hashicorp/terraform:1.0.0'
  dir: 'scripts/cloudbuild/gce-tf'
  args: ['fmt', '-recursive', '-check', 'diff']

- id: 'Terraform Plan with output file'
  name: 'hashicorp/terraform:1.0.0'
  dir: 'scripts/cloudbuild/gce-tf'
  args: ['plan', '-out tf_plan']

- id: 'Push Terraform Output file to JFrog Artifactory'
  name: 'docker.bintray.io/jfrog/artifactory-cpp-ce'
  dir: 'scripts/cloudbuild/gce-tf'
  entrypoint: sh
  args: 
    - '-c'
    - |
      curl -H "${_JFROG_API}" -T tf_plan "${_JFROG_ARTIFACTORY_URL}/tf/tf_plan"
